version: '3.8'

services:
  machine1:
    image: alpine
    container_name: machine1
    command: ["sleep", "infinity"]
    networks:
      - net

  machine2:
    image: alpine
    container_name: machine2
    command: ["sleep", "infinity"]
    networks:
      - net

  machine3:
    image: alpine
    container_name: machine3
    command: ["sleep", "infinity"]
    networks:
      - net

networks:
  net:
    driver: bridge