services:
  machine1:
    image: alpine
    command: ["sleep", "infinity"]
    networks:
      - net1

  machine2:
    image: alpine
    command: ["sleep", "infinity"]
    networks:
      - net1
      - net2

  machine3:
    image: alpine
    command: ["sleep", "infinity"]
    networks:
      - net2
      - internet

networks:
  net1:
    driver: bridge
  net2:
    driver: bridge
  internet:
    driver: bridge
    # By default, bridge networks allow internet access