# This Dockerfile sets up a single Ubuntu image.
# To create a network of three Ubuntu containers (with one as a router),
# you need a docker-compose.yml file to orchestrate the network.
# Below is the Dockerfile for the Ubuntu image.

FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y iproute2 iputils-ping net-tools sudo && \
    apt-get clean

# Enable IP forwarding for the router container
RUN echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf

CMD [ "bash" ]