services:
  client:
    build: ./client
    cap_add:
      - NET_ADMIN  
    privileged: true        # Simplest way to allow forwarding
    volumes:
      -  ../python/covert_client/:/opt/client  # Live bind mount for client source
      - ./captures:/captures
    command: /entrypoint.sh
    networks:
      internal_net:
        ipv4_address: 10.200.0.2
    ports:
      - "5901:5901"
      - "6901:6901"

  proxy:
    build: ./proxy
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN  
    privileged: true        # Simplest way to allow forwarding
    volumes:
      -  ../python/covert_proxy:/opt/proxy  # Live bind mount for proxy source
      - ./captures:/captures
    command: /entrypoint.sh
    networks:
      internal_net:
        ipv4_address: 10.200.0.3
      default: {}

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
