
services:
  client:
    build: ./client
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ../python/covert_client/:/opt/client
      - ./captures:/captures
    command: /entrypoint.sh
    networks:
      internal_net:
        ipv4_address: 10.200.0.2
    ports:
      - "5901:5901"
      - "6901:6901"

  proxy:
    build: ./proxy
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    volumes:
      - ../python/covert_proxy:/opt/proxy
      - ./captures:/captures
      - ./resolv.conf:/etc/resolv.conf:ro   # Mount a fixed resolv.conf
    command: /entrypoint.sh
    networks:
      internal_net:
        ipv4_address: 10.200.0.3
      default: {}

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
